spring:
  data:
    mongodb:
      uri: mongodb+srv://realvoice:realvoice@realvoice.ju1uzh6.mongodb.net/RealVoice?retryWrites=true&w=majority&appName=RealVoice
  servlet:
    multipart:
      max-request-size: 10MB  # 최대 요청 크기 설정 (10MB 예시)
      max-file-size: 10MB      # 최대 파일 크기 설정 (10MB 예시)